# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ado

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'


# - task: AzureRmWebAppDeployment@5
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'AMVM Visual Studio Enterprise Subscription(2ea0a635-4fe2-4a14-9ed4-6ec6440da7a0)'
#     appType: 'webApp'
#     WebAppName: 'sjh-azure-pipeline'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'



stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'pipelines-dotnet-core.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'AMVM Visual Studio Enterprise Subscription(2ea0a635-4fe2-4a14-9ed4-6ec6440da7a0)'
              appType: 'webApp'
              appName: 'sjh-azure-pipeline'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'

